language:
  - python
python:
  - 2.7
install:
  - pip install 'unittest2'
  - pip install "flake8${FLAKE8_VERSION}"
  - pip install 'flake8-blind-except'
  - pip install "argparse==1.2.1"
  - pip install "logging==0.4.9.6"
  - pip install "requests==2.0.1"
  - pip install "SQLAlchemy==1.2.17"
  - pip install "urllib3==1.6"
  - pip install "retrying==1.3.3"
  - pip install "mysqlclient==1.4.1"
  - pip install "web.py==0.39"
  - pip install "futures==3.2.0"
  - pip install "stomp.py==4.1.21"
before_script:
  - pwd
  - ls -lah
  - pip freeze
  - flake8 --help
  - if [[ $FLAKE8_CONFIG != ".flake8" ]]; then rm .flake8; fi
  - flake8 --config $FLAKE8_CONFIG lib/ess/
script:
  - bash tools/test/test.sh
matrix:
  include:
  - python: 2.7
    env: FLAKE8_CONFIG=.flake8 FLAKE8_VERSION="<=3.5.0"
  exclude:
  - python: 2.7
